### PR TITLE
Talks schema migration

### PR DESCRIPTION
**Pull request by andrewjprice**
Create Talks table.

### CODE REVIEW

**Comment by denvaar** [comment]
This is awesome. Let's merge it after Alex's PR during the meeting tomorrow. And I think we don't need the mix.lock file.

**Comment by denvaar** [comment]
And now that I think of it, it would save us some time to use `phx.gen.context` instead, because it will also generate some code to allow us to query the database easier. It will also generate some tests.

**Comment by denvaar** [comment]
We can merge this as soon as conflicts are resolved. I don't think mix.lock should be part of the changes, but I'm not sure why it's there

**Comment by alex-kovshovik** [comment]
@andrew-price01 probably need to re-open this PR, create a new one, because of (probably) rebase that went wrong:

monosnap 2018-04-05 20-55-54

**Comment by denvaar** [comment]
:) lets do it together tomorrow

**Pull request closed without merging**
